# Generated by Django 4.2.3 on 2023-07-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('idProductor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreContacto', models.CharField(blank=True, max_length=100, null=True)),
                ('rut', models.CharField(blank=True, max_length=15, null=True)),
                ('razonSocial', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('rubro', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Productores',
            },
        ),
    ]
