# Generated by Django 4.2.3 on 2023-07-11 17:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Crédito', 'Crédito'), ('Debito', 'Debito'), ('PayPal', 'PayPal'), ('Mach', 'Mach')], default='Crédito', max_length=15)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('mediopedido', models.CharField(choices=[('Telefono', 'Telefono'), ('E-mail', 'E-mail'), ('Web', 'Web')], default='Web', max_length=15)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Preparación', 'En Preparación'), ('En Despacho', 'En Despacho'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=15)),
                ('deleted', models.BooleanField(default=False)),
                ('pedido_staff', models.BooleanField(default=False)),
                ('is_modificable', models.BooleanField(default=True)),
                ('precio_total', models.IntegerField(default=0)),
                ('idcliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('idpedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.pedido')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.producto')),
            ],
        ),
    ]
