# Generated by Django 4.2.3 on 2023-07-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_pedido_detallepedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='deleted',
        ),
    ]
